// Code generated by "stringer -linecomment -type Hero"; DO NOT EDIT.

package d2enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeroNone-0]
	_ = x[HeroBarbarian-1]
	_ = x[HeroNecromancer-2]
	_ = x[HeroPaladin-3]
	_ = x[HeroAssassin-4]
	_ = x[HeroSorceress-5]
	_ = x[HeroAmazon-6]
	_ = x[HeroDruid-7]
	_ = x[HeroDevil-8]
}

const _Hero_name = "BarbarianNecromancerPaladinAssassinSorceressAmazonDruidDevil"

var _Hero_index = [...]uint8{0, 0, 9, 20, 27, 35, 44, 50, 55, 60}

func (i Hero) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Hero_index)-1 {
		return "Hero(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hero_name[_Hero_index[idx]:_Hero_index[idx+1]]
}
